const recipes = [
    { name: 'Nasi Goreng', level: 1, ingredients: 'Rice → Cooked Rice', rewards: { xp: 50, money: 100 }},
    { name: 'Kue Cubir', level: 1, ingredients: 'Tapioca Flour → Dough', rewards: { xp: 40, money: 80 }},
    { name: 'Rendang', level: 1, ingredients: 'Coconut → Coconut Milk', rewards: { xp: 60, money: 120 }},
    { name: 'Kolak', level: 2, ingredients: 'Sweet Potato → Mashed Sweet Potato', rewards: { xp: 55, money: 110 }},
    { name: 'Ayam Penyet', level: 2, ingredients: 'Chicken → Fried Chicken', rewards: { xp: 70, money: 140 }},
    { name: 'Tempeh Mendoan', level: 2, ingredients: 'Tempeh → Fried Tempeh', rewards: { xp: 65, money: 130 }},
    { name: 'Martabak Telur', level: 3, ingredients: 'Egg → Scrambled Egg', rewards: { xp: 75, money: 150 }},
    { name: 'Ikan Bakar', level: 3, ingredients: 'Fish → Grilled Fish', rewards: { xp: 80, money: 160 }},
    { name: 'Arepas', level: 3, ingredients: 'Corn → Corn Dough', rewards: { xp: 85, money: 170 }},
    { name: 'Tahu Tempe', level: 4, ingredients: 'Tofu → Fried Tofu', rewards: { xp: 90, money: 180 }},
    { name: 'Cendol', level: 4, ingredients: 'Palm Sugar → Syrup', rewards: { xp: 95, money: 190 }},
    { name: 'Kue Lumpur', level: 4, ingredients: 'Flour → Dough', rewards: { xp: 100, money: 200 }},
    { name: 'Sate', level: 5, ingredients: 'Beef → Marinated Beef', rewards: { xp: 110, money: 220 }},
    { name: 'Ubi Rebus', level: 5, ingredients: 'Cassava → Cooked Cassava', rewards: { xp: 115, money: 230 }},
    { name: 'Gulai', level: 5, ingredients: 'Coconut → Coconut Milk', rewards: { xp: 120, money: 240 }},
];
